<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AppDiaria.Domain\AppDiaria.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOS\Ejercicios\" />
    <Folder Include="DTOS\Recordatorio\" />
    <Folder Include="DTOS\Tarea\" />
    <Folder Include="Interfaces\InterfacesSeccionEntrenamientos\" />
    <Folder Include="UseCases\Ejercicios\" />
    <Folder Include="UseCases\RutinaEjercicio\" />
    <Folder Include="UseCases\Rutinas\" />
    <Folder Include="UseCases\Tareas\RutinaEjercicioUseCase\" />
    <Folder Include="UseCases\Usuarios\Login\" />
    <Folder Include="Validadores\SeccionRutinas\" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
