// <auto-generated />
using System;
using AppDiaria.Infreaestructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDiaria.Infreaestructure.Migrations
{
    [DbContext(typeof(AppDiariaContext))]
    [Migration("20260215191805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechayHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.EntrenamientoRutina", b =>
                {
                    b.Property<int>("EntrenamientoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RutinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntrenamientoId", "RutinaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("EntrenamientoRutinas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.RutinaEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriasPorRepeticion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RutinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Recordatorio", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Recordatorios")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.EntrenamientoRutina", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", "Entrenamiento")
                        .WithMany("EntrenamientoRutinas")
                        .HasForeignKey("EntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDiaria.Domain.Entidades.Rutinas.Rutina", "Rutina")
                        .WithMany("EntrenamientoRutinas")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenamiento");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.RutinaEjercicio", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Rutinas.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDiaria.Domain.Entidades.Rutinas.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Tarea", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Tareas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", b =>
                {
                    b.Navigation("EntrenamientoRutinas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Rutina", b =>
                {
                    b.Navigation("EntrenamientoRutinas");

                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Entrenamientos");

                    b.Navigation("Recordatorios");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
