// <auto-generated />
using System;
using AppDiaria.Infreaestructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDiaria.Infreaestructure.Migrations
{
    [DbContext(typeof(AppDiariaContext))]
    [Migration("20260131193830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechayHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriasPerdidas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Series")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dia")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntrenamientosId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntrenamientosId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Ejercicio", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Rutinas.Rutina", null)
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Rutina", b =>
                {
                    b.HasOne("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", null)
                        .WithMany("Rutinas")
                        .HasForeignKey("EntrenamientosId");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Entrenamientos", b =>
                {
                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("AppDiaria.Domain.Entidades.Rutinas.Rutina", b =>
                {
                    b.Navigation("Ejercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
